#SpeedMin 20
#SpeedDefault 100
#SpeedMax 500
#PitchMin 50
#PitchDefault 100
#PitchMax 300
#IntonationMin 0
#IntonationDefault 100
#IntonationMax 140
GeneralGapFactor 0
CommaGapFactor50
DotGapFactor 100
SemicolonGapFactor 20
ColonGapFactor 40
QuestionGapFactor 100
ExclamationGapFactor 100
IntonationalGapFactor 0
#Flags 3
